import Section from '../../components/Section';

const About = () => (
  <Section className="About" title="About" id="about">
    <p>
      I am a software engineer with a passion for building scalable and
      efficient applications. I enjoy working with modern web technologies and
      continuously learning new skills. This is placeholder text for this
      section generated by AI.
    </p>
  </Section>
);

export default About;
