import Section from './components/Section';

const App = () => (
  <>
    <Section className="Cover" centered>
      <h1>Punit Shah</h1>
      <p>Software Engineer</p>
    </Section>
    <Section className="About" title="About">
      <p>
        I am a software engineer with a passion for building scalable and
        efficient applications. I enjoy working with modern web technologies and
        continuously learning new skills. This is placeholder text for this
        section generated by AI.
      </p>
    </Section>
    <Section className="Projects" title="Projects">
      <p>
        Coming soon! This section will showcase my projects and contributions.
      </p>
    </Section>
    <Section className="Contact" title="Contact">
      <p>
        Contact form coming soon! Until then, you can reach me at{' '}
        <a href="mailto:***REMOVED***">***REMOVED***</a>
      </p>
    </Section>
  </>
);

export default App;
